language: ruby
rvm:
  - 2.1.0
install: true
env:
  global:
    secure: "4cYZDJvt5Y7qhGaiuZGCc8RSNKLsoFOidw+x8jGraPcg1UaSbWvR0kfev9Is8hpBuBLI6G3O7o3tz2gYhhBx9V5QaP0wbt9nLlTtcALCkRSa40iusT8qjX7iRs7KF5c7xXbyz63VWptygwCi/KRQZHuKTVZiEG9inqcLBJzdOoU="
  - ddir="tmp-deploy"
  - src-branch="gh-pages-src"
  - target-branch="gh-pages"
  - project="pallet/pallet"
