language: ruby
rvm:
  - 2.1.0
install:
  - sudo pip install Pygments
env:
  global:
    - secure: "4cYZDJvt5Y7qhGaiuZGCc8RSNKLsoFOidw+x8jGraPcg1UaSbWvR0kfev9Is8hpBuBLI6G3O7o3tz2gYhhBx9V5QaP0wbt9nLlTtcALCkRSa40iusT8qjX7iRs7KF5c7xXbyz63VWptygwCi/KRQZHuKTVZiEG9inqcLBJzdOoU="
    - "DDIR=tmp-deploy"
    - "TARGET_BRANCH=gh-pages"
    - "PROJECT=pallet/pallet"
before_script:
  - rm -rf $DDIR
script:
  - git clone https://github.com/$PROJECT.git --branch $TARGET_BRANCH --single-branch $DDIR
  - bundle install
  - bundle exec jekyll doctor
  - bundle exec jekyll build --verbose --trace --destination $DDIR
  - ls -lr $DDIR
after_success:
  - cd $DDIR
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add -u .
  - git config user.email "tbatchelli@acm.org"
  - git config user.name "tbatchelli"
  - git commit -am "new-site-deployed" --allow-empty
  - git push origin $TARGET_BRANCH 2>&1
after_script:
  - rm -rf $DDIR
notifications:
  irc: irc.freenode.org#pallet
